#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

REQUIRED_SNIPPETS = {
    "README.md": [
        "Governance & Determinism Guarantees (Current State)",
        "ADAAD_DISPATCH_LATENCY_BUDGET_MS",
        "ADAAD_DETERMINISTIC_LOCK",
        "<!-- ADAAD_VERSION_INFOBOX:START -->",
        "<!-- ADAAD_VERSION_INFOBOX:END -->",
    ],
    "runtime/README.md": [
        "Deterministic Guarantees",
    ],
    "ui/README.md": [
        "Aponi URL is derived from runtime constants",
    ],
    "docs/releases/RELEASE_AUDIT_CHECKLIST.md": [
        "Replay on two independent environments",
        "Constitution checksum verified",
    ],
    "docs/DOCS_VISUAL_STYLE_GUIDE.md": [
        "Approved badge style",
        "Alt-text requirements",
    ],
    "docs/assets/IMAGE_PROVENANCE.md": [
        "adaad-banner.svg",
    ],
}

INFOBOX_START = "<!-- ADAAD_VERSION_INFOBOX:START -->"
INFOBOX_END = "<!-- ADAAD_VERSION_INFOBOX:END -->"
INFOBOX_SYNC_CONTEXT_NOTE = (
    "<!-- Sync context: generated from current git metadata at sync time; "
    "reflects last sync context only, not arbitrary local working trees. -->"
)
REQUIRED_INFOBOX_FIELDS = (
    "Current version",
    "Released",
    "Release SHA",
    "Release Branch",
)


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Validate strict README and release-doc snippet alignment.")
    parser.add_argument(
        "--format",
        choices=("text", "json"),
        default="json",
        help="Output format. Defaults to json for CI readability.",
    )
    return parser


def _extract_version_infobox(readme_text: str) -> str | None:
    pattern = re.compile(
        re.escape(INFOBOX_START) + r"(?P<block>.*?)" + re.escape(INFOBOX_END),
        re.DOTALL,
    )
    match = pattern.search(readme_text)
    if not match:
        return None
    return match.group("block")


def _parse_infobox_fields(block: str) -> dict[str, str]:
    fields: dict[str, str] = {}
    for match in re.finditer(r"\|\s*\*\*(?P<key>[^*]+)\*\*\s*\|\s*(?P<val>[^|]+?)\s*\|", block):
        fields[match.group("key").strip()] = match.group("val").strip().strip("`")
    return fields


def _validate_readme_infobox(readme_text: str, missing: list[str]) -> None:
    block = _extract_version_infobox(readme_text)
    if block is None:
        missing.append("malformed_infobox:README.md:missing_version_infobox_block")
        return

    if "Auto-generated by scripts/sync_docs_on_merge.py" not in block:
        missing.append("malformed_infobox:README.md:missing_autogen_marker")

    if INFOBOX_SYNC_CONTEXT_NOTE not in block:
        missing.append("malformed_infobox:README.md:missing_sync_context_note")

    if "**Git SHA**" in block or "**Branch**" in block:
        missing.append("malformed_infobox:README.md:legacy_git_field_names_present")

    fields = _parse_infobox_fields(block)
    missing_fields = [name for name in REQUIRED_INFOBOX_FIELDS if name not in fields]
    if missing_fields:
        missing.append(
            "malformed_infobox:README.md:missing_fields:" + ",".join(missing_fields)
        )

    unexpected = sorted(set(fields) - set(REQUIRED_INFOBOX_FIELDS))
    if unexpected:
        missing.append(
            "malformed_infobox:README.md:unexpected_fields:" + ",".join(unexpected)
        )

    report_meta_path = ROOT / "governance" / "report_version.json"
    if not report_meta_path.exists():
        missing.append("stale_infobox:governance/report_version.json:missing")
        return

    try:
        report_meta = json.loads(report_meta_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        missing.append(f"stale_infobox:governance/report_version.json:invalid_json:{exc}")
        return

    if report_meta.get("version_source") != "governance/report_version.json":
        missing.append("stale_infobox:governance/report_version.json:bad_version_source")

    expected_mapping = {
        "Current version": str(report_meta.get("report_version", "")).strip(),
        "Released": str(report_meta.get("last_sync_date", "")).strip(),
        "Release SHA": str(report_meta.get("last_sync_sha", "")).strip(),
    }

    for field_name, expected_value in expected_mapping.items():
        observed = fields.get(field_name, "")
        if expected_value and observed != expected_value:
            missing.append(
                f"stale_infobox:README.md:{field_name}:expected={expected_value}:observed={observed}"
            )


def _emit(missing: list[str], output_format: str) -> None:
    if output_format == "json":
        payload = {
            "validator": "readme_alignment",
            "ok": not missing,
            "missing": sorted(missing),
        }
        print(json.dumps(payload, sort_keys=True))
        return

    if missing:
        for item in sorted(missing):
            print(item)
        return
    print("readme_alignment_ok")


def main() -> int:
    args = _build_parser().parse_args()
    missing: list[str] = []
    try:
        readme_text = ""
        for rel, snippets in sorted(REQUIRED_SNIPPETS.items()):
            path = ROOT / rel
            if not path.exists():
                missing.append(f"missing_file:{rel}")
                continue
            text = path.read_text(encoding="utf-8")
            if rel == "README.md":
                readme_text = text
            for snippet in snippets:
                if snippet not in text:
                    missing.append(f"missing_snippet:{rel}:{snippet}")

        if readme_text:
            _validate_readme_infobox(readme_text, missing)
    except Exception as exc:  # fail closed
        missing.append(f"validator_error:{exc.__class__.__name__}:{exc}")

    _emit(missing=missing, output_format=args.format)
    return 1 if missing else 0


if __name__ == "__main__":
    raise SystemExit(main())
